# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
defaults: &defaults
  docker: # run the steps with Docker
    - image: cibuilds/drupal:latest

  environment:
    COMPOSER_BIN: ~/blt/vendor/bin
    # BLT_DIR: ~/blt/vendor/acquia/blt
    BLT_DIR: ~/blt/.circleci/
    BUILD_DIR: ~/blt

  working_directory: ~/blt

jobs:
  before_install:
    <<: *defaults
    steps:
      - checkout
      - run: composer self-update
      - run: composer validate --no-check-all --ansi
      - run: composer install
        # Exit build early if only documentation was changed in a Pull Request.
      - run: source ${BLT_DIR}/scripts/circleci/exit_early
  install:
    <<: *defaults
    steps:
      - run: source ${BLT_DIR}/scripts/circleci/setup_environment
      - run: source ${BLT_DIR}/scripts/circleci/setup_project

  script:
    <<: *defaults
    steps:
      - run: source ${BLT_DIR}/scripts/circleci/run_tests

  deploy:
    <<: *defaults
    steps:
      - run: source ${BLT_DIR}/scripts/circleci/deploys

workflows:
  version: 2
  build_tests:
    jobs:
      - before_install
      - install:
          requires:
            - before_install
      - script:
          requires:
            - install
      - deploy:
          requires:
            - script
          filters:
            branches:
              only:
                - master
                - develop
